### GET request all Users
GET http://localhost:8085/user
Accept: application/json


### GET request User by ID
GET http://localhost:8085/user/2
Accept: application/json


### Send POST request with json body
POST http://localhost:8085/user
Content-Type: application/json

{
  "name": "Ivan",
  "lastName": "Ivanov",
  "mobile" : "123765"
}

### Send PUT request with json body
PUT http://localhost:8085/user/3
Content-Type: application/json

{
  "mobile" : "999777"
}

### Send DELETE request with json body
DELETE http://localhost:8085/user/4

### Get User by Name
GET http://localhost:8085/user/Ivanov
Accept: application/json

