###All users
GET  http://localhost:8085/user
Accept: Application/json


###ById
GET  http://localhost:8085/user/2
Accept: Application/json


###Post Create User
POST  http://localhost:8085/user
Accept: Application/json

{"name":"Petr",
 "LastName":"Petrov",
 "Mobile":"908768"}

###
GET  http://localhost:8085/user
Accept: Application/json




###
GET  http://localhost:8085/user
Accept: Application/json
